package utils

const (
	CPU_CORES_CPUINFO_ERROR  = -2
	LAVG_TREND_CPUINFO_ERROR = -1
	SUCCEEDED                = 0
	LAVG_TREND_ERROR         = 1
	LAVG_TREND_INCREASING    = 2
	LAVG_TREND_NORMAL        = 3
	FILE_EXT_ERR             = 4
	FILE_EXT_NOT_PROVIDED    = 5
	FILE_EXT_ASTERISK        = 6
	FILE_PREFIX_ERR          = 8
	FILE_PREFIX_ASTERISK     = 9
	DB_CONN_ERR              = 10
	DB_USERNAME_NOT_PROVIDED = 11
	DB_NAME_NOT_PROVIDED     = 12
	DB_HOSTNAME_NOT_PROVIDED = 14
	LAVG_LOAD_LEVEL_YELLOW   = 70
	DEL_FILE_LIST_E_SLEEP    = 60

	KEY_ENV = "APP_ENV"
	APP_NAME = "taskfactory"
)
